trading_symbol: "NIFTY24DEC23500PE"  # Replace with your desired trading symbol
no_of_days: 5                        # Number of days of historical data to fetch
candle_time_duration: "15minute"     # Candle time duration (e.g., '5minute', '15minute', '1hr', '1D')